server {
    listen 80;
    server_name localhost;

    location / {
        proxy_pass http://backend:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_connect_timeout 5s;
    }
    location /nginx-health {
    access_log off;
    return 200 "nginx healthy\n";
    add_header Content-Type text/plain;
    }
    # Эндпоинт для healthcheck
    location /nginx-python-health {
        proxy_pass http://backend:8080/nginx-health;
        access_log off;
    }
} 

