server {
    listen ${NGINX_PORT};
    server_name localhost;

    location / {
        proxy_pass http://backend:${BACKEND_PORT};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_connect_timeout 5s;
    }
    
    # Эндпоинт для healthcheck
    location /nginx-health {
        proxy_pass http://backend:${BACKEND_PORT}/nginx-health;
        access_log off;
    }
} 
